### ISSUE TITLE
Timing follow-up

### ISSUE THREAD

**Issue by icweaver** [machkouroke/Wordle_Solver#3]
Hey @machkouroke! Here are some simple micro-benchmarks that I am finding from our exercism discussion, I hope they are helpful!

## Native Python

```python
In [1]: %timeit proba()
7.01 µs ± 37.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

<details>

```python
> micromamba activate .CondaPkg/env/

> ipython

In [1]: from itertools import product

In [2]: def proba():
   ...:     x = ('gris', 'vert', 'jaune')
   ...:     return list(product(x, repeat=5))
   ...: 

In [3]: %timeit proba()
```
</details>

## PyCall.jl

```julia
julia> @btime proba();
  736.903 μs (7065 allocations: 175.56 KiB)
```

<details>

```julia
julia> using PyCall, BenchmarkTools

julia> py"""
       from itertools import product
       def proba():
           return list(product(('gris', 'vert', 'jaune'), repeat=5))
       """

julia> proba = py"proba"

julia> @btime proba();
```

</details>

## PythonCall.jl

```julia
julia> @btime proba();
  5.193 μs (1 allocation: 16 bytes)
```

<details>

```julia
julia> using PythonCall, BenchmarkTools

julia> @pyexec """
       global proba, product
       from itertools import product
       def proba():
           x = ('gris', 'vert', 'jaune')
           return list(product(x, repeat=5))
       """

julia> proba = @pyeval "proba"

julia> @btime proba();
```

</details>

Note: All Python runs using v3.10.5

## Native Julia

```julia
julia> @btime proba_jl();
  3.150 μs (6 allocations: 36.84 KiB)
```

<details>

```julia
julia> using Base.Iterators, BenchmarkTools

julia> function proba_jl()
           x = ("gris", "vert", "jaune")
           product(repeated(x, 5)...) |> Ref |> flatten |> collect
       end

ulia> @btime proba_jl();
```

</details>

So on my end at least, I am getting about the same speed using PythonCall.jl, and about a 2x speed-up wih native Julia, vs. native Python

**Comment by machkouroke** [comment]
@icweaver Hello IcWeaver I will answer you here regarding the project so as not to deviate as agreed.

> One difference I am seeing (and the reason that everything is flipped from the Python version) is because Python lays its memory out in a row-major format, while Julia is column-major. This means that when the Iterators.product is computed, its essentially expanding this nested loop column-wise, while Python expands it row-wise:

Exactly this is what I could see by analyzing the first line of the list. I had heard of it before but I had no idea it could have been so impactful.


Here are the results I finally got by integrating the functions into the code
## PyCall.jl
```julia 
@btime best_word = find_best_word(wordle)
# 84.734 s (882218592 allocations: 28.05 GiB)
```

## Julia native
```julia 
@btime best_word = find_best_word(wordle)
# 82.935 s (882218592 allocations: 28.05 GiB)
```
The difference is minimal but is where. I think the slowness was because I always let bits of python code be evaluated even though I wasn't using it. This time I commented it out and indeed the pure julia version is slightly faster
However, I tried to use PythonCall but compared to Pycall we don't have a direct conversion to the native type of julia so it had to be done for the list and all its components. I haven't done it yet but I will do it to analyze

**Comment by machkouroke** [comment]
That's great @icweaver I'll consider it for improvements
